### ISSUE TITLE
プレゼン内容の共有

### ISSUE THREAD

**Issue by tkbtk-kic** [FOSS-B-team/github_practice#10]
なんか山下さんと岡さんの間で、それぞれでプレゼン資料とか作って授業でまとめるみたいな話があるそうですが、ここで意見を出し合いませんか？内容がかぶるかもしれないし
#### プレゼン内容
- **作成物の説明を少々**
- **どんな作業フローを使ったか？なぜその作業フローを選んだか？**
- **作業はどのように進めているか？**
- **どんなトラブルに遭遇したか？どのようにトラブルを解決したか？**
- **Githubを使った開発を通じて、気づいたことなど**

**Comment by 16006kic** [comment]
作業中のトラブル解決と,githubの開発を通じで気付いたことを,各自がちょこちょこ意見を出していけばプレゼン資料自体は割と簡単に作れそうですね.

**Comment by tkbtk-kic** [comment]
もうこれも　ファイル作ります？
...作りますか

作るんでいい感じに編集してくださいね

**Comment by 16006kic** [comment]
プログラミング基礎の講義にみんな出席していたのでこのページのことを伝えておきました.
伝えなかったらおそらく気付いてなかったでしょう:)

**Comment by tkbtk-kic** [comment]
[presentation.md](https://github.com/FOSS-B-team/github_practice/blob/master/presentation.md)
作った。
これを編集するか、このIssuesページに投稿する感じでいいんじゃない？

**Comment by 16006kic** [comment]
pullリクエストして誰かにmergeしてもらえばいいのかな.
あってるならリクエスト出しといたから誰かお願いします.
