### ISSUE TITLE
issuesとは　+ プレゼンについて

### ISSUE THREAD

**Issue by tkbtk-kic** [FOSS-B-team/github_practice#5]
issuesは問題とか課題とかいう意味で　そんな感じのものをここに書いて共有するスペースです

問題を一つ提起しておきましょう

プレゼンは誰がやるのですか？

**Comment by 16006kic** [comment]
先ほどgithubpractice.cをmergeしました。

プレゼンは発表やりたい人がやるか,いないならじゃんけんか何かできめましょう

誰が発表するのかを決めるのも大事だけどプレゼン資料の作成もしないとダメですね
次のOSS基礎論の1コマ目で作るのかな？

**Comment by tkbtk-kic** [comment]
90分あれば一応のものはできそうではありますね
ちなみに私はやりたくないです
